# Notebook: Linear Algebra

![](pictures/logo300px.png)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction" data-toc-modified-id="Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#What-is-a-matrix?" data-toc-modified-id="What-is-a-matrix?-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>What is a matrix?</a></span><ul class="toc-item"><li><span><a href="#Create-a-matrix-by-setting-a-shape" data-toc-modified-id="Create-a-matrix-by-setting-a-shape-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Create a matrix by setting a shape</a></span></li><li><span><a href="#Getting-the-number-of-independent-row/colums,-the-rank" data-toc-modified-id="Getting-the-number-of-independent-row/colums,-the-rank-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Getting the number of independent row/colums, the rank</a></span></li><li><span><a href="#The-inverse-of-a-matrix-with-function-inv()" data-toc-modified-id="The-inverse-of-a-matrix-with-function-inv()-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>The inverse of a matrix with function <code>inv()</code></a></span></li></ul></li><li><span><a href="#Multiplications-with-NumPy-arrays" data-toc-modified-id="Multiplications-with-NumPy-arrays-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Multiplications with NumPy arrays</a></span><ul class="toc-item"><li><span><a href="#Array-broadcasting" data-toc-modified-id="Array-broadcasting-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Array broadcasting</a></span><ul class="toc-item"><li><span><a href="#scalar-and-array" data-toc-modified-id="scalar-and-array-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>scalar and array</a></span></li><li><span><a href="#array-time-array-(elementswise)" data-toc-modified-id="array-time-array-(elementswise)-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span>array time array (elementswise)</a></span></li><li><span><a href="#array-times-array,-different-dimensions" data-toc-modified-id="array-times-array,-different-dimensions-3.1.3"><span class="toc-item-num">3.1.3&nbsp;&nbsp;</span>array times array, different dimensions</a></span></li></ul></li></ul></li><li><span><a href="#Linear-algebra-operations" data-toc-modified-id="Linear-algebra-operations-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Linear algebra operations</a></span><ul class="toc-item"><li><span><a href="#Dot-product-of-arrays" data-toc-modified-id="Dot-product-of-arrays-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Dot product of arrays</a></span></li><li><span><a href="#Dot-product-matrix-and-inverse-is-unit-matrix.-The-dot()-function" data-toc-modified-id="Dot-product-matrix-and-inverse-is-unit-matrix.-The-dot()-function-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Dot product matrix and inverse is unit matrix. The dot() function</a></span></li><li><span><a href="#A-unit-matrix-is-created-with-NumPy-function--identity()" data-toc-modified-id="A-unit-matrix-is-created-with-NumPy-function--identity()-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>A unit matrix is created with NumPy function  identity()</a></span></li><li><span><a href="#Tranpose-of-a-matrix,-using-the--T-attribute-of-the-ndarray-object" data-toc-modified-id="Tranpose-of-a-matrix,-using-the--T-attribute-of-the-ndarray-object-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Tranpose of a matrix, using the  <em>T</em> attribute of the ndarray object</a></span><ul class="toc-item"><li><span><a href="#Checking-the-shape-of-a-transposed-matrix" data-toc-modified-id="Checking-the-shape-of-a-transposed-matrix-4.4.1"><span class="toc-item-num">4.4.1&nbsp;&nbsp;</span>Checking the shape of a transposed matrix</a></span></li></ul></li><li><span><a href="#Calculating-the-determinant-of-a-matrix" data-toc-modified-id="Calculating-the-determinant-of-a-matrix-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Calculating the determinant of a matrix</a></span></li><li><span><a href="#Do-it-yourself-exercise-1:" data-toc-modified-id="Do-it-yourself-exercise-1:-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span><font color="red">Do it yourself exercise 1:</font></a></span></li><li><span><a href="#Solving-linear-equations-with-solve()" data-toc-modified-id="Solving-linear-equations-with-solve()-4.7"><span class="toc-item-num">4.7&nbsp;&nbsp;</span>Solving linear equations with <code>solve()</code></a></span></li><li><span><a href="#When-is-a-matrix-orthogonal?" data-toc-modified-id="When-is-a-matrix-orthogonal?-4.8"><span class="toc-item-num">4.8&nbsp;&nbsp;</span>When is a matrix orthogonal?</a></span></li><li><span><a href="#Eigenvalue-and-Eigenvector" data-toc-modified-id="Eigenvalue-and-Eigenvector-4.9"><span class="toc-item-num">4.9&nbsp;&nbsp;</span>Eigenvalue and Eigenvector</a></span></li><li><span><a href="#Cross-product-of-two-vectors" data-toc-modified-id="Cross-product-of-two-vectors-4.10"><span class="toc-item-num">4.10&nbsp;&nbsp;</span>Cross product of two vectors</a></span></li><li><span><a href="#Length-of-a-vector,-the-norm" data-toc-modified-id="Length-of-a-vector,-the-norm-4.11"><span class="toc-item-num">4.11&nbsp;&nbsp;</span>Length of a vector, the norm</a></span></li></ul></li></ul></div>

## Introduction

The module used for Linear Algebra is module ``linalg`` from package NumPy. We use alias ``la`` so that we don't have to type ``linalg`` each time we use a function of this module.

In [1]:
import numpy as np
from numpy import linalg as la

# We want to suppress printing of small floating point values using scientific notation 
np.set_printoptions(suppress=True)

## What is a matrix?

In numerical analysis we work a lot with matrices. There is a ``matrix`` module in NumPy but there is a tendency to get rid of it because it does not mix well with the ``linalg`` module which is considered as a core module and works for ``ndarray``'s of any dimension and not just two dimensional structures. 

Also, some functionality (like the dot product) has been optimized in ``linalg`` and that can be an essential feature when working with huge data sets.

So first let us examine how close matrix notation is to indexing ``ndarray`` (NumPy) arrays.

The entry of a (mathematical) matrix *A* that is stored in the *i* -th
row and the *j*-th column is called the *i*, *j*
entry or *(i,j)*-th entry of *A*.
This is written as $A_{i,j}$ or in a 2dim NumPy array: ``A[i,j]``

    | A11  A12   .....  A1m 
    | A21  A22   .....  A2m 
    |  .                    
    |  .                    
    | An1  An2   .....  Anm 

So we have 'n' rows and 'm' columns. The **shape** of this matrix
can be written as the tuple (n,m).

Think of a mnemonic yourself. A personal one is ``roll call``. Looks like a matrix, roll starts with the r of row and call starts with the c of column. The sound of the words (roll->row, call->col) also helps you to remember this.

![roll call](./pictures/rollcall.jpg)

**Rank**  
The column rank of a matrix ``A`` is the maximal number of linearly independent columns of ``A``.
Likewise, the row rank is the maximal number of linearly independent rows of ``A``.
Since the column rank and the row rank are always equal, they are simply called the **rank** of A.
The rank of an ``n x m`` matrix is at most the lesser of ``m`` and ``n``.
A matrix where one of the dimensions equals one is often
called a **vector**.

**Indexing**  
Note that in the literature we start writing indices at 1, but in in Python
(and many other languages) the first index is starts with '0'.
So entry `A11` corresponds to ``A[0,0]`` if A is a Python Matrix.

### Create a matrix by setting a shape

With some 1 dimensional array of data we can create a matrix by setting a shape. We show two ways. The first is to explicitly set the shape in the shape tuple of an array or we use method ``reshape``.

In [2]:
rows = 4; cols = 5
M = np.arange(rows*cols)
M.shape = (rows,cols)
print("M=")
print(M)

M=
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [3]:
M = np.array([1,2, 3,4]).reshape(2,2)
print("M=")
print(M)

M=
[[1 2]
 [3 4]]


### Getting the number of independent row/colums, the rank

The rank is calculated with function ``matrix_rank()``:

In [4]:
rank = la.matrix_rank(M)
print("Rank of this matrix is:", rank)

Rank of this matrix is: 2


### The inverse of a matrix with function ``inv()``

The inverse of a matrix is one of the most important features in linear algebra and in numerical analysis.
We calculate the inverse with function ``inv()``. If we use it a lot, then we import the function in the current name space for convenience and cleaner code:

In [5]:
from numpy.linalg import inv
Minv = inv(M)
print("The inverse of M=")
print(Minv)

The inverse of M=
[[-2.   1. ]
 [ 1.5 -0.5]]


## Multiplications with NumPy arrays

Before we continue with matrix multiplications we need a short intermezzo about multiplications with ``ndarray`` objects.

### Array broadcasting
Usually operations on n-dimensional arrays are done elementwise and therefore require two arrays with the same dimensions. But there are exceptions which we will discuss here.

#### scalar and array

In [6]:
print(M)
print()
print(M*2)

[[1 2]
 [3 4]]

[[2 4]
 [6 8]]


#### array time array (elementswise)

In [7]:
print(M)
print()
print(M*M)

[[1 2]
 [3 4]]

[[ 1  4]
 [ 9 16]]


#### array times array, different dimensions
If two arrays share one dimension, multiplication will be applied along the other dimension. This is called array broadcasting.  
The smaller array will be extended in row or column direction until it matches the first array.

In [8]:
M = np.arange(2*3).reshape(2,3)
v = np.array([10,20,30])
print(f"M=\n{M}\n")
print(f"v=\n{v}\n")
print(f"M*v=\n{M*v}\n")
print(f"v*M=\n{v*M}\n")

M=
[[0 1 2]
 [3 4 5]]

v=
[10 20 30]

M*v=
[[  0  20  60]
 [ 30  80 150]]

v*M=
[[  0  20  60]
 [ 30  80 150]]



Now we create a version of ``v`` with two rows and 1 column to demonstrate that the multiplication will be applied in the 
other direction.

In [9]:
M = np.arange(2*3).reshape(2,3)
v = np.array([10,20]).reshape(2,1)
print(f"M=\n{M}\n")
print(f"v=\n{v}\n")
print(f"M*v=\n{M*v}\n")
print(f"v*M=\n{v*M}\n")

M=
[[0 1 2]
 [3 4 5]]

v=
[[10]
 [20]]

M*v=
[[  0  10  20]
 [ 60  80 100]]

v*M=
[[  0  10  20]
 [ 60  80 100]]



**Note** Array broadcasting applies not only to multiplication but to all operators. Remember that the operations work elementwise.

## Linear algebra operations
### Dot product of arrays

If you multiply two matrices with the ``*`` operator then the multiplication is applied elements-wise. 
This is **not** a dot product.
A dot product for two vectors/matrices is also called the *inner product*. If A and B are Matrices, then element (i,j) in the dot product is given by:

$$(AB)_{ij}=\sum _{r=1}^{n}a_{ir}b_{rj}=a_{i1}b_{1j}+a_{i2}b_{2j}+\cdots +a_{in}b_{nj}$$

Note that dot products are associative. If we have three matrices A, B and C, then

$$ (\mathbf {AB} )\mathbf {C} =\mathbf {A} (\mathbf {BC} )$$

This implies that we don't need parentheses to force the order of evaluation.  

The dot product of two arrays can be calculated with Numpy's function and method ``dot()``  
https://numpy.org/doc/stable/reference/generated/numpy.dot.html  

Assuming we have two arrays ``A`` and ``B`` then we can write:

* ``C = np.dot(A,B)``  (as a function)
* ``C = A.dot(B)``     (as a method)
* ``C = A@B``          (if ``A`` and ``B`` are matrices)

Some specific outcomes:

* If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).
* If both a and b are 2-D arrays, it is matrix multiplication, but using ``numpy.matmul`` or ``A @ B`` is preferred.
* If either a or b is 0-D (scalar), it is equivalent to multiply and using ``numpy.multiply(a, b)`` or ``A * B`` is preferred.
* If ``A`` is an N-D array and ``B`` is a 1-D array, it is a sum product over the last axis of ``A`` and ``B``.
* If ``A`` is an N-D array and ``B`` is an M-D array (where M>=2), it is a sum product over the last axis of ``A`` and the second-to-last axis of ``B``:


If we need dot products for more than two matrices, we can also use the function ``numpy.linalg.multi_dot()``.

### Dot product matrix and inverse is unit matrix. The dot() function

In [10]:
M = np.array([[1,-2,4],[2,0,2],[5,3,0]])
print(f"M=\n{M}")
Minv = inv(M)
print(f"\nInverse of M=\n{Minv}")

E = M@Minv      # Use it as a method
print(f"\nM@Minv should be the unit matrix:\n{E}")

a = np.array([1,2,-1])
b = np.array([0,1,2])
print(f"\nInner product of a and b: {np.dot(a,b)}   (If 0 then they are orthogonal)")

# Concatenate dot products
R = M@Minv@M
print(f"\nConcatenated dot products MM^(-1)M should give M again:\n{R}")

# Or use multi_dot
R = la.multi_dot((M, Minv, M))
print(f"\nConcatenated dot products with multi_dot() should give M again:\n{R}")

M=
[[ 1 -2  4]
 [ 2  0  2]
 [ 5  3  0]]

Inverse of M=
[[ 3.  -6.   2. ]
 [-5.  10.  -3. ]
 [-3.   6.5 -2. ]]

M@Minv should be the unit matrix:
[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]

Inner product of a and b: 0   (If 0 then they are orthogonal)

Concatenated dot products MM^(-1)M should give M again:
[[ 1. -2.  4.]
 [ 2. -0.  2.]
 [ 5.  3.  0.]]

Concatenated dot products with multi_dot() should give M again:
[[ 1. -2.  4.]
 [ 2. -0.  2.]
 [ 5.  3.  0.]]


### A unit matrix is created with NumPy function  identity()
A unit matrix is created with NumPy's function ``identity(n)`` where n the dimension of the square array is :

In [11]:
Munit = np.identity(2)
print(f"Rank 2 unit matrix:\n {Munit}")

Rank 2 unit matrix:
 [[1. 0.]
 [0. 1.]]


### Tranpose of a matrix, using the  *T* attribute of the ndarray object

You probably know what the transpose of a matrix is. There we just swap rows and columns. It is a bit 
harder to understand what the transpose is of an array with more than two dimensions.
The trick is to get the shape tuple of an array. Then reverse the order in the shape tuple.
For an 1 dimensional array, the transpose is the same as the original array, so in fact a transpose 
is defined for arrays of arbitrary dimension. 

To get the transpose of an array one can use a method ``np.transpose()`` (not from the linalg module because each ndarray object has an transpose), but it is easier to use attribute ``T``.

In [12]:
Mtrans = M.T
print(f"Transpose of M with M.T:\n{Mtrans}")
print(f"Transpose with method transpose(M):\n{np.transpose(M)}")

Transpose of M with M.T:
[[ 1  2  5]
 [-2  0  3]
 [ 4  2  0]]
Transpose with method transpose(M):
[[ 1  2  5]
 [-2  0  3]
 [ 4  2  0]]


#### Checking the shape of a transposed matrix

In [13]:
# Transpose of n-dimensional data structures:
A = np.arange(24).reshape(2,3,4)
print("Shape of A:", A.shape)
Atrans = A.T
print("Shape of A:", Atrans.shape)

Shape of A: (2, 3, 4)
Shape of A: (4, 3, 2)


### Calculating the determinant of a matrix

In [14]:
det = la.det(M)
print(f"Determinant of M is: {det:.6f}")

Determinant of M is: -2.000000


### <font color='red'>Do it yourself exercise 1:</font>

Given an array ``A`` and a vector ``b`` then if ``A.x = b`` we find solution ``x`` with ``x = inv(A).b``. <br>
Use this to solve the following
set of equations:

$$x+3y+5z = 10\\ 2x+5y+z =  8\\ 2x+3y+8z  =  3$$

**Solution:**

In [15]:
A = np.array([1,3,5,2,5,1,2,3,8]).reshape(3,3)
print(f"Matrix A:\n{A}")
b = np.array([10,8,3])
Ainv = inv(A)
xyz = Ainv@b
print(f"\nSolution: x, y, z = {xyz}")
print(f"\nShorter: x, y, z = la.inv(A).dot(b) = {inv(A)@b}")

Matrix A:
[[1 3 5]
 [2 5 1]
 [2 3 8]]

Solution: x, y, z = [-9.28  5.16  0.76]

Shorter: x, y, z = la.inv(A).dot(b) = [-9.28  5.16  0.76]


###  Solving linear equations with ``solve()``

The linear algebra module provides a function ``solve()`` which solves systems of linear equations like the example in the previous cell. Function ``solve()`` is a faster and more stable routine. Given a matrix ``A`` and a vector ``b`` the syntax to solve the system is:

    xyz = la.solve(A,b)
    
Let's try it with the same system of equations:    

In [16]:
A = np.array([1,3,5,2,5,1,2,3,8]).reshape(3,3)
b = np.array([10,8,3])
X = la.solve(A, b)  # Unpacking is also possible with NumPy arrays
print(A, ".(x,y,z) =", X)
x, y, z = X         # Unpack tuple  
print(f"\nSolution x, y, z={x:.6f}, {y:.6f}, {z:.6f}")

[[1 3 5]
 [2 5 1]
 [2 3 8]] .(x,y,z) = [-9.28  5.16  0.76]

Solution x, y, z=-9.280000, 5.160000, 0.760000


### When is a matrix orthogonal?

A n x n matrix is  orthogonal if $A.A^T = I$ where $I$ is the identity matrix. From this we can derive that 
$A^{-1} = A^T$.<br>
For this category of matrices, it is simple to find an inverse by applying an transpose (which is always much faster).

To compare two arrays, one can use the NumPy function ``np.array_equal()`` or if you suspect rounding errors use
``np.allclose()``.

In [2]:
import numpy as np
from numpy.linalg import inv
A = np.array([2,-2,1,1,2,2,2,1,-2]).reshape(3,3)
A = A/3
print(f"Matrix A:\n{A}")
print(f"\nA.AT should be the identity matrix:\n{A@A.T}\n{A@A.T == np.identity(3)}")
print(f"\nInverse of A:\n{inv(A)}")
print(f"\nis equal to the transpose:\n{A.T}")
print(f"\nAlternative check with function array_equal(): {np.array_equal(A.T, inv(A))}")
print(f"\nAlternative check with function allclose(): {np.allclose(A.T, inv(A))}")

Matrix A:
[[ 0.66666667 -0.66666667  0.33333333]
 [ 0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]

A.AT should be the identity matrix:
[[1.00000000e+00 1.54197642e-17 1.23358114e-17]
 [1.54197642e-17 1.00000000e+00 2.46716228e-17]
 [1.23358114e-17 2.46716228e-17 1.00000000e+00]]
[[False False False]
 [False False False]
 [False False False]]

Inverse of A:
[[ 0.66666667  0.33333333  0.66666667]
 [-0.66666667  0.66666667  0.33333333]
 [ 0.33333333  0.66666667 -0.66666667]]

is equal to the transpose:
[[ 0.66666667  0.33333333  0.66666667]
 [-0.66666667  0.66666667  0.33333333]
 [ 0.33333333  0.66666667 -0.66666667]]

Alternative check with function array_equal(): False

Alternative check with function allclose(): True


### Eigenvalue and Eigenvector

An Eigenvector of a square matrix ``A`` is a non-zero vector ``v`` that, 
when the matrix is multiplied by ``v``, the result is constant: $\lambda . v$.

$$  A.v = \lambda v $$
   
In Linear Algebra courses you learn(ed) how to find values of  $\lambda$ and how to
construct the Eigenvectors $v$.

We use ``numpy.linalg.eig`` to find the the Eigenvalues and the normalized (i.e. with unit length) Eigenvectors.
Let's try to find the Eigenvalues and Eigenvectors of Matrix ``A`` with:


In [18]:
A = np.array([5,8,16,4,1,8,-4,-4,-11]).reshape(3,3)
print(A)

[[  5   8  16]
 [  4   1   8]
 [ -4  -4 -11]]


In [19]:
Lambda, v = la.eig(A)
print("Lambda = ", Lambda)
print(f"\nEigenvectors:\n{v}")

Lambda =  [ 1.+0.j -3.+0.j -3.-0.j]

Eigenvectors:
[[ 0.81649658+0.j          0.14036888-0.55580947j  0.14036888+0.55580947j]
 [ 0.40824829+0.j         -0.71521317+0.j         -0.71521317-0.j        ]
 [-0.40824829+0.j          0.28742215+0.27790473j  0.28742215-0.27790473j]]


In [20]:
# Unpack the three vectors
v1, v2, v3 = v.T
print(v1)
print(v2)
print(v3)
print("\nProof of (A.v == Lambda.v):")
print(np.allclose(A@v1, Lambda[0]*v1))
print(np.allclose(A@v2, Lambda[1]*v2))
print(np.allclose(A@v3, Lambda[2]*v3))

[ 0.81649658+0.j  0.40824829+0.j -0.40824829+0.j]
[ 0.14036888-0.55580947j -0.71521317+0.j          0.28742215+0.27790473j]
[ 0.14036888+0.55580947j -0.71521317-0.j          0.28742215-0.27790473j]

Proof of (A.v == Lambda.v):
True
True
True


### Cross product of two vectors

With the cross product of two vectors we find a new vector that is orthogonal to the two vectors.

In [21]:
v1 = np.array((2,3,4))
v2 = np.array((5,6,7))

v3 = np.cross(v1, v2)
print("Vector orthogonal to v1 and v2:", v3)

Vector orthogonal to v1 and v2: [-3  6 -3]


### Length of a vector, the norm
Module ``linalg`` provides a function ``norm`` to calculate the length of a vector. 

In [22]:
from numpy.linalg import norm
L = norm(v1)
print(f"The length of v1={L}")

The length of v1=5.385164807134504


In one of the course exercises we will deal with most of the discussed functions and techniques when applied to rotation matrices.